theme: minima
title: Practice Site
author: MelissaJr
email: emayyethomas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is just a practice website. I made this because I am just following steps.

# social links
twitter_username: <Strong>N/A</strong> # DO NOT include the @ character, or else the build will fail!
github_username:  MelissaJr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
